1. lamda function

In [ ]:
x= lambda a,b:a*b
print(x(3,4))

12


In [ ]:
def myfunc(n):
  return lambda a: a*n
value2= myfunc(2)
value3= myfunc(3)
print(value2(10))
print(value3(11))

20
33


2. filter function

In [ ]:
list1=list(range(0,10))
nlist=list(filter(lambda x: (x%2==0),list1))
print(nlist)

[0, 2, 4, 6, 8]


3. IMPORTING NUMPY

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

In [ ]:
a.size

3

In [ ]:
a.shape

(3,)

4. Two dimensional arrays

In [ ]:
b=np.array([[1.3,2.4],[0.3,4.1]])

In [ ]:


b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [ ]:

type(b)

numpy.ndarray

In [ ]:


b.dtype

dtype('float64')

In [ ]:
b.ndim

2

In [ ]:


b.size

4

In [ ]:
b.shape

(2, 2)

In [ ]:
b.itemsize

8

In [ ]:
c=np.array([[1,2,3],[4,5,6]])

In [ ]:

c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d=np.array(((1,2,3),(4,5,6)))

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
e=np.array([(1,2,3),(4,5,6),[7,8,9]])

In [ ]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
g=np.array([['a','b'],['c','d']])

In [ ]:
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

5. Inbuilt functions

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.random.random(3)

array([0.25548687, 0.07855125, 0.05539075])

In [ ]:
np.random.random((3,3))

array([[0.88469599, 0.94361233, 0.86239195],
       [0.3464141 , 0.24542199, 0.14719238],
       [0.56670986, 0.72977631, 0.49213816]])

6. BASIC OPERATIONS ON NUMPY ARRAY

In [ ]:
a=np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a+4

array([4, 5, 6, 7])

In [ ]:
a*2

array([0, 2, 4, 6])

In [ ]:
b=np.arange(4,8)

In [ ]:
b

array([4, 5, 6, 7])

In [ ]:
a+b

array([ 4,  6,  8, 10])

In [ ]:
a-b

array([-4, -4, -4, -4])

In [ ]:
a*b

array([ 0,  5, 12, 21])

7. Increment and Decrement operators

In [ ]:
a=np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a+=1

In [ ]:
a

array([1, 2, 3, 4])

8. Universal functions

In [ ]:
a=np.arange(1,5)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

8. Aggregrate Function

In [ ]:
a=np.array([3.3,4.5,1.2,5.7,0.3])

In [ ]:
a.sum()

15.0

In [ ]:
a.min()

0.3

In [ ]:
a.max()

5.7

In [ ]:
a.mean()

3.0

In [ ]:
a.std()

2.0079840636817816

9. INDEXING, SLICING and ITERATING

In [ ]:
a=np.arange(10,16)

In [ ]:
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[4]

14

In [ ]:
a[[1,3,4]]

array([11, 13, 14])

2d array

In [ ]:
A=np.arange(10,19).reshape((3,3))

In [ ]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[1,2]

15

SLICING

In [ ]:
a=np.arange(10,16)

In [ ]:
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[1:5]

array([11, 12, 13, 14])

In [ ]:
a[1:5:2]

array([11, 13])

In [ ]:
a[:5:2]

array([10, 12, 14])

In [ ]:
a[:5:]

array([10, 11, 12, 13, 14])

2D ARRAY SLICING

In [ ]:
A=np.arange(10,19).reshape((3,3))

In [ ]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[0,:]

array([10, 11, 12])

In [ ]:
A[:,0]

array([10, 13, 16])

In [ ]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

ITERATING an ARRAY

In [ ]:
for i in a:
  print(i)

10
11
12
13
14
15


In [ ]:
for row in A:
  print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [ ]:
for item in A.flat:
  print(item)

10
11
12
13
14
15
16
17
18


10. apply_along_axis()

In [ ]:
np.apply_along_axis(np.mean,axis=0,arr=A)

array([13., 14., 15.])

In [ ]:
np.apply_along_axis(np.mean,axis=1,arr=A)

array([11., 14., 17.])

In [ ]:
def foo(x):
  return x/2

In [ ]:
np.apply_along_axis(foo,axis=1,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [ ]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

11. SHAPE MANIPULATION

In [ ]:
a=np.random.random(12)

In [ ]:
a

array([0.10777275, 0.34931601, 0.0084759 , 0.55334823, 0.69882838,
       0.05346712, 0.829939  , 0.14399201, 0.49712382, 0.06732555,
       0.03037653, 0.26233199])

In [ ]:
A=a.reshape(3,4)

In [ ]:
A

array([[0.10777275, 0.34931601, 0.0084759 , 0.55334823],
       [0.69882838, 0.05346712, 0.829939  , 0.14399201],
       [0.49712382, 0.06732555, 0.03037653, 0.26233199]])

In [ ]:
print(a.ravel())

[0.10777275 0.34931601 0.0084759  0.55334823 0.69882838 0.05346712
 0.829939   0.14399201 0.49712382 0.06732555 0.03037653 0.26233199]


In [ ]:
A.transpose()

array([[0.10777275, 0.69882838, 0.49712382],
       [0.34931601, 0.05346712, 0.06732555],
       [0.0084759 , 0.829939  , 0.03037653],
       [0.55334823, 0.14399201, 0.26233199]])

12. Array Manipulation

In [ ]:
A=np.ones((3,3))

In [ ]:
B=np.zeros((3,3))

In [ ]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
a=np.array([0,1,2])
b=np.array([3,4,5])
c=np.array([6,7,8])
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

13. Splitting Arrays

In [ ]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
[B,C]=np.hsplit(A,2)

In [ ]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
[B,C]=np.vsplit(A,2)

In [ ]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

14. split() function

In [ ]:
[A1,A2,A3]=np.split(A,[1,3],axis=1)

In [ ]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [ ]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
[A1,A2,A3]=np.split(A,[1,3],axis=0)

In [ ]:
A1

array([[0, 1, 2, 3]])

In [ ]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A3

array([[12, 13, 14, 15]])



> THUS, every program in NUMP is executed

