Declaring a series

In [ ]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [ ]:
s = pd.Series([12,-4,7,9],
index=['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

 view Index and values seperatly

In [ ]:
s.values


array([12, -4,  7,  9])

In [ ]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

creating a series from ndarray

In [ ]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print (s)

0    a
1    b
2    c
3    d
dtype: object


Dictionary Objects as Series

In [ ]:
import pandas as pd
calories = {"day1": 420, "day2": 380, 
"day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data,index=['b','c','d','a'])
print (s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


Selecting the Internal Elements

In [ ]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'])
s


a    12
b    -4
c     7
d     9
dtype: int64

In [ ]:
s[2]


7

In [ ]:
s['b']


-4

In [ ]:
s[0:2]

a    12
b    -4
dtype: int64

In [ ]:
s[['b','c']]


b   -4
c    7
dtype: int64

Assigning Values to the Elements


In [ ]:
s[1] = 0
s


a    12
b     0
c     7
d     9
dtype: int64

In [ ]:
 s['b'] = 1
 s


a    12
b     1
c     7
d     9
dtype: int64

Filtering Values

In [ ]:
s[s > 8]

a    12
d     9
dtype: int64

Operations and Mathematical Functions

In [ ]:
s / 2

a    6.0
b    0.5
c    3.5
d    4.5
dtype: float64

In [ ]:
np.log(s)


a    2.484907
b    0.000000
c    1.945910
d    2.197225
dtype: float64

Evaluating Values

In [ ]:
 serd = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [ ]:
serd.unique()

array([1, 0, 2, 3])

In [ ]:
serd.value_counts()

2    2
1    2
3    1
0    1
dtype: int64

In [ ]:
serd.isin([0,3])

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool

In [ ]:
serd[serd.isin([0,3])]


white     0
yellow    3
dtype: int64

NaN Values


In [ ]:
s2 = pd.Series([5,-3,np.NaN,14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [ ]:
s2.isnull()


0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
 s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [ ]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [ ]:
s2[s2.isnull()]

2   NaN
dtype: float64

creatig simple pandas data frame

In [ ]:
import pandas as pd
data = {
"calories": [420, 380, 390],
"duration": [50, 40, 45]
}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
data = {'color' : 
['blue','green','yellow','red','white'],
'object' : 
['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
#load data into a DataFrame object:
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [ ]:
Create a Data Frame from Lists

In [ ]:
import pandas as pd
data = [1,2,3,4,5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

Create a DataFrame from Dict of ndarrays / Lists

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

In [ ]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df

Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

Create a DataFrame from List of Dicts

In [ ]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 
20}]
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [ ]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, 
index=['first', 'second'])
df

a   b     c
first   1   2   NaN
second  5  10  20.0

In [ ]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
#With two column indices, values same as dictionary keys
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
#With two column indices with one index with other name
df2 = pd.DataFrame(data, index=['first','second'], columns=['a', 'b1'])
df1
df2

a  b1
first   1 NaN
second  5 NaN

Create a DataFrame from Dict of Series

In [9]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),'two' : pd.Series([1, 2, 3, 4],index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

Create a DataFrame from Dict of Series

In [10]:
nestdict = { 'red': { 2012: 22, 2013: 33 },'white': { 2011: 13, 2012: 22, 2013: 16},'blue': {2011: 17, 2012: 27, 2013: 18}}
frame2 = pd.DataFrame(nestdict)
frame2

red  white  blue
2012  22.0     22    27
2013  33.0     16    18
2011   NaN     13    17

Selecting Elements

In [12]:
import numpy as np
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [19]:
frame.columns

Index(['ball', 'pen', 'pencil', 'paper'], dtype='object')

In [20]:
frame.index

Index(['red', 'blue', 'yellow', 'white'], dtype='object')

In [21]:
frame.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
frame[0:1]

ball  pen  pencil  paper
red     0    1       2      3

In [29]:
frame[1:3]

ball  pen  pencil  paper
blue       4    5       6      7
yellow     8    9      10     11

iloc attribute

In [30]:
frame.iloc[2:4]

ball  pen  pencil  paper
yellow     8    9      10     11
white     12   13      14     15

Assigning Values


In [32]:
frame.index.name = 'id'
frame.columns.name = 'item'
frame

item    ball  pen  pencil  paper
id                              
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [34]:
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
df = df.append(df2)
df

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [48]:
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
# Adding a new column to an existing DataFrame object with column label by passing new series
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df



Adding a new column by passing as Series:


one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN